WeddingMenu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeddingMenu.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Statistic");
            }
            return View();
        }

        public ActionResult Statistic()
        {
            return View();

        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Menu()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WeddingMenu/Controllers/InvitationController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WeddingMenu.Models;

namespace WeddingMenu.Controllers
{
    public class InvitationController : Controller
    {
        private ApplicationDbContext _applicationDbContext = null;
        public ApplicationDbContext applicationDbContext
        {
            get
            {
                return _applicationDbContext ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set { _applicationDbContext = value; }
        }
        public InvitationController()
        {

        }
     
        // GET: Invitation
        public async Task<ActionResult> Index(string id)
        {
            //0KPQstCw0LbQsNC10LzQsNGPINCb0Y7QtNC80LjQu9Cw
            //
            string greeting = "";
            DatabaseModels.Invitation inv = await applicationDbContext.Invitations.Where(e => e.ID.Equals(id)).Select(e => e).FirstOrDefaultAsync();
            if (inv != null)
            {
                greeting = inv.InvitationMessage;
            }
     
            byte[] data = Convert.FromBase64String(greeting);
            string decodedString = Encoding.UTF8.GetString(data);
            ViewBag.Greeting = decodedString;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("SaveInvitation")]
        public async Task SaveInvitationAsync(string id, string encode)
        {          

            DatabaseModels.Invitation inv =  await applicationDbContext.Invitations.Where(e => e.ID.Equals(id)).Select(e => e).FirstOrDefaultAsync();
            if (inv == null)
            {
                inv = new DatabaseModels.Invitation();
                inv.ID = id;
                applicationDbContext.Invitations.Add(inv);
            }            
            inv.InvitationMessage = encode;
            await applicationDbContext.SaveChangesAsync();

        }

        [HttpGet, Authorize, ActionName("GetInvitationList")]
        public async Task<JsonResult> GetInvitationListAsync()
        {
            var ap = await applicationDbContext.Invitations.Select(e => new { @invitationMessage = e.InvitationMessage, @id =e.ID }).ToListAsync();
            return Json(ap, JsonRequestBehavior.AllowGet);
        }
    }
}

WeddingMenu/Controllers/MenuController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WeddingMenu.DatabaseModels;
using WeddingMenu.Models;

namespace WeddingMenu.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext _applicationDbContext = null;
        public ApplicationDbContext applicationDbContext
        {
            get
            {
                return _applicationDbContext ?? HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            }
            private set { _applicationDbContext = value; }
        }
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost, Authorize, ValidateAntiForgeryToken, ActionName("SaveNewMenu")]
        public async Task SaveNewMenuAsync(string name, string description, string weight)
        {
            var dish = await applicationDbContext.Dishes.Where(e => e.Name == name).FirstOrDefaultAsync();
            if (dish == null)
            {
                Dish di = new Dish();
                di.Name = name;
                di.Description = description;
                di.Weight = weight;
                di.ID = Guid.NewGuid().ToString();
                applicationDbContext.Dishes.Add(di);
            }
            else
            {
                dish.Description = description;
            }
            await applicationDbContext.SaveChangesAsync();

        }
        [HttpGet, ActionName("GetMenu")]
        public async Task<ActionResult> GetMenuAsync(string id )
        {
            ViewBag.id = id;
            return View();
        }

        [HttpGet, ActionName("GetMenuList")]
        public async Task<JsonResult> GetMenuListAsync()
        {
            var ap = await applicationDbContext.Dishes.OrderBy(or=>or.Name).Select(e => new { @name = e.Name, @description = e.Description, @weight = e.Weight }).ToListAsync();
            return Json(ap, JsonRequestBehavior.AllowGet);
        }
    }
}

WeddingMenu/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WeddingMenu/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WeddingMenu/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WeddingMenu/Views/Home/Menu.cshtml
@{
    ViewBag.Title = "Меню";
}
<div class="card card-default">
    <div class="card-heading">Меню</div>
    <div class="input-group mb-3">
        <input id="inputText" type="text" class="form-control" placeholder="Наименование" aria-label="s username" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <input id="inputText2" type="text" class="form-control" placeholder="Описание" aria-label="Описание" aria-describedby="basic-addon2">
        </div>    
        <div class="input-group-append">
            <input id="inputText3" type="text" class="form-control" placeholder="Вес" aria-label="Вес" aria-describedby="basic-addon2">
        </div>
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="button-addon2">Добавить</button>
        </div>
    </div>
    <div class="card-body">
        <div id="listId" class="list-group">

            @*<a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">List group item heading</h5>
                    <small>3 days ago</small>
                </div>
                <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
                <small>Donec id elit non mi porta.</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">List group item heading</h5>
                    <small class="text-muted">3 days ago</small>
                </div>
                <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
                <small class="text-muted">Donec id elit non mi porta.</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">List group item heading</h5>
                    <small class="text-muted">3 days ago</small>
                </div>
                <p class="mb-1">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
                <small class="text-muted">Donec id elit non mi porta.</small>
            </a>*@
        </div>


    </div>
</div>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

@section scripts{
    <script>

        $(document).ready(() => {
            Menu.prototype.initMenu('@Url.Action("SaveNewMenu","Menu")');
            Menu.loadMenu('@Url.Action("GetMenuList", "Menu")');
        });



    </script>

}

WeddingMenu/Views/Home/Statistic.cshtml
@{
    ViewBag.Title = "Statistic";
}
<div class="card card-default">
    <div class="card-heading">Статистика</div>
    <div class="input-group mb-3">
        <input id="inviteText" type="text" class="form-control" placeholder="Приглашение" aria-label="Приглашение" aria-describedby="basic-addon2">
        @*<div class="input-group-append">
            <span class="input-group-text" id="urlD"></span>
        </div>*@
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button" id="button-addon2">Добавить</button>
        </div>
    </div>
    <div class="card-body">
        <div id="listId" class="list-group">
           
        </div>


    </div>
</div>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

@section scripts{
    <script>
        
        $(document).ready(() => {
            Invitation.prototype.initStatistics('@Url.Action("SaveInvitation","Invitation")');
            Invitation.loadInvitations('@Url.Action("GetInvitationList", "Invitation")');
        });


       
    </script>

}